module.exports = [
    {
        title: "Largest Element in Array",
        topic: "Arrays",
        difficulty: "Easy",
        description: "Given an array A[] of size n. The task is to find the largest element in it.",
        points: "1",
        example: "n = 5, A[] = {1,8,7,56,90}",
        complexity: "O(N)",
        tags: "Arrays",
    },
    {
        title: "Sum of numbers in string",
        topic: "Strings",
        difficulty: "Easy",
        description: "Given a string str containing alphanumeric characters. The task is to calculate the sum of all the numbers present in the string.",
        points: "1",
        example: "str = 1abc23",
        complexity: "O(N)",
        tags: "Strings",
    },
    {
        title: "Sum of numbers in Array",
        topic: "Strings",
        difficulty: "Easy",
        description: "Given a string str containing alphanumeric characters. The task is to calculate the sum of all the numbers present in the string.",
        points: "1",
        example: "str = 1abc23",
        complexity: "O(N)",
        tags: "Strings",
    },
    {
        title: "Sum of numbers in Wppw",
        topic: "Strings",
        difficulty: "Easy",
        description: "Given a string str containing alphanumeric characters. The task is to calculate the sum of all the numbers present in the string.",
        points: "1",
        example: "str = 1abc23",
        complexity: "O(N)",
        tags: "Strings",
    },
];